ALTER TABLE employees
ALTER COLUMN first_name SET NOT NULL,
ALTER COLUMN last_name SET NOT NULL,
ALTER COLUMN job_position SET NOT NULL,
ALTER COLUMN start_date SET NOT NULL,
ALTER COLUMN birth_date SET NOT NULL
